# Generated by Django 4.0.1 on 2022-01-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, default='default-article-img.png', null=True, upload_to=''),
        ),
    ]
